apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mongo
spec:
  selector:
    matchLabels:
      app: flask-mongo
  template:
    metadata:
      labels:
        app: flask-mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /Temp/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: thomas-flask-demo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: flask-mongo
spec:
  selector:
    app: flask-mongo
  ports:
    - port: 27017
      targetPort: 27017