apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
    azurestorageaccountname: aG91Z2hzYQ==
    azurestorageaccountkey: YldIdlVSdVdlbWZBS1I1ZXVFTUJNWi84TmlRQjVTRlRJbHc4d3hMc0xLT0lVL2VNSzJpNVIxVkY3UkRYQUozaThmci9ZUTJVNjNkbktkTWo2R3orcHc9PQ==