kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongosc
provisioner: file.csi.azure.com
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  storageaccounttype: Standard_LRS

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ''
#  azureFile:
#    secretName: mongodb-secret
#    shareName: mongodb-files
#    readOnly: false
#  mountOptions:
#  - dir_mode=0777
#  - file_mode=0777
#  - uid=1000
#  - gid=1000
  hostPath:
    path: /data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ''
  volumeName: mongopv