kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongosc
provisioner: file.csi.azure.com
reclaimPolicy: Delete
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ''
  azureFile:
    secretName: mongodb-secret
    shareName: mongodb-files
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ''
  volumeName: mongopv