apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowpv
spec:
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: azure-file-airflow-dags
    shareName: airflow-dags
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: airflowpvc
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowpvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: airflow-dags
  resources:
    requests:
      storage: 5Gi
  storageClassName: ''

---