apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow-scheduler
    chart: airflow-0.9.0
    release: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: nhstcontainerregistry.azurecr.io/nhst-airflow:v2.2.3
          ports:
            - containerPort: 7000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgresUser
                  name: airflow-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresPassword
                  name: airflow-secret
          volumeMounts:
            - mountPath: /usr/local/airflow/logs
              name: dags-data
      volumes:
        - name: dags-data
          persistentVolumeClaim:
            claimName: azure-managed-disk
