apiVersion: v1
kind: PersistentVolume
metadata:
  name: thomas-flask-demo-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Temp/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thomas-flask-demo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: ''